///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InstitucionDistanciaModel {
/*
{
  "idInsitucion": 1,
  "idDireccion": 1,
  "institucion": "HOSPITAL CIVIL",
  "direccion": "Republica de costa rica 325",
  "colonia": "Quintero",
  "ciudad": "Tlaquepaque",
  "estado": "Jalisco",
  "latitud": 20.569447376699006,
  "longitud": -103.2272873133507,
  "imagen": "/uploads/FB_IMG_1626638999498_ff97bc17f5.jpg",
  "codigoPostal": "45550",
  "distancia": 10.644579939561089
} 
*/

  int? idInsitucion;
  int? idDireccion;
  String? institucion;
  String? direccion;
  String? colonia;
  String? ciudad;
  String? estado;
  double? latitud;
  double? longitud;
  String? imagen;
  String? codigoPostal;
  double? distancia;

  InstitucionDistanciaModel({
    this.idInsitucion,
    this.idDireccion,
    this.institucion,
    this.direccion,
    this.colonia,
    this.ciudad,
    this.estado,
    this.latitud,
    this.longitud,
    this.imagen,
    this.codigoPostal,
    this.distancia,
  });
  InstitucionDistanciaModel.fromJson(Map<String, dynamic> json) {
    idInsitucion = json['idInsitucion']?.toInt();
    idDireccion = json['idDireccion']?.toInt();
    institucion = json['institucion']?.toString();
    direccion = json['direccion']?.toString();
    colonia = json['colonia']?.toString();
    ciudad = json['ciudad']?.toString();
    estado = json['estado']?.toString();
    latitud = json['latitud']?.toDouble();
    longitud = json['longitud']?.toDouble();
    imagen = json['imagen']?.toString();
    codigoPostal = json['codigoPostal']?.toString();
    distancia = json['distancia']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['idInsitucion'] = idInsitucion;
    data['idDireccion'] = idDireccion;
    data['institucion'] = institucion;
    data['direccion'] = direccion;
    data['colonia'] = colonia;
    data['ciudad'] = ciudad;
    data['estado'] = estado;
    data['latitud'] = latitud;
    data['longitud'] = longitud;
    data['imagen'] = imagen;
    data['codigoPostal'] = codigoPostal;
    data['distancia'] = distancia;
    return data;
  }
}
