///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ResponseGeocodingBusquedaMapBoxModelFeaturesContext {
/*
{
  "id": "postcode.11250836121368760",
  "text": "45570"
} 
*/

  String? id;
  String? text;

  ResponseGeocodingBusquedaMapBoxModelFeaturesContext({
    this.id,
    this.text,
  });
  ResponseGeocodingBusquedaMapBoxModelFeaturesContext.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    text = json['text']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['text'] = text;
    return data;
  }
}

class ResponseGeocodingBusquedaMapBoxModelFeaturesGeometry {
/*
{
  "type": "Point",
  "coordinates": [
    -103.306746
  ],
  "interpolated": true
} 
*/

  String? type;
  List<double?>? coordinates;
  bool? interpolated;

  ResponseGeocodingBusquedaMapBoxModelFeaturesGeometry({
    this.type,
    this.coordinates,
    this.interpolated,
  });
  ResponseGeocodingBusquedaMapBoxModelFeaturesGeometry.fromJson(
      Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
    interpolated = json['interpolated'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['coordinates'] = arr0;
    }
    data['interpolated'] = interpolated;
    return data;
  }
}

class ResponseGeocodingBusquedaMapBoxModelFeaturesProperties {
/*
{
  "accuracy": "interpolated"
} 
*/

  String? accuracy;

  ResponseGeocodingBusquedaMapBoxModelFeaturesProperties({
    this.accuracy,
  });
  ResponseGeocodingBusquedaMapBoxModelFeaturesProperties.fromJson(
      Map<String, dynamic> json) {
    accuracy = json['accuracy']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['accuracy'] = accuracy;
    return data;
  }
}

class ResponseGeocodingBusquedaMapBoxModelFeatures {
/*
{
  "id": "address.1719818010",
  "type": "Feature",
  "place_type": [
    "address"
  ],
  "relevance": 0.679012,
  "properties": {
    "accuracy": "interpolated"
  },
  "text": "República De Costa Rica",
  "place_name": "República De Costa Rica 325, 45570 Tlaquepaque, Jalisco, Mexico",
  "center": [
    -103.306746
  ],
  "geometry": {
    "type": "Point",
    "coordinates": [
      -103.306746
    ],
    "interpolated": true
  },
  "address": "325",
  "context": [
    {
      "id": "postcode.11250836121368760",
      "text": "45570"
    }
  ]
} 
*/

  String? id;
  String? type;
  List<String?>? placeType;
  double? relevance;
  ResponseGeocodingBusquedaMapBoxModelFeaturesProperties? properties;
  String? text;
  String? placeName;
  List<double?>? center;
  ResponseGeocodingBusquedaMapBoxModelFeaturesGeometry? geometry;
  String? address;
  List<ResponseGeocodingBusquedaMapBoxModelFeaturesContext?>? context;

  ResponseGeocodingBusquedaMapBoxModelFeatures({
    this.id,
    this.type,
    this.placeType,
    this.relevance,
    this.properties,
    this.text,
    this.placeName,
    this.center,
    this.geometry,
    this.address,
    this.context,
  });
  ResponseGeocodingBusquedaMapBoxModelFeatures.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    type = json['type']?.toString();
    if (json['place_type'] != null) {
      final v = json['place_type'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      placeType = arr0;
    }
    relevance = json['relevance']?.toDouble();
    properties = (json['properties'] != null)
        ? ResponseGeocodingBusquedaMapBoxModelFeaturesProperties.fromJson(
            json['properties'])
        : null;
    text = json['text']?.toString();
    placeName = json['place_name']?.toString();
    if (json['center'] != null) {
      final v = json['center'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      center = arr0;
    }
    geometry = (json['geometry'] != null)
        ? ResponseGeocodingBusquedaMapBoxModelFeaturesGeometry.fromJson(
            json['geometry'])
        : null;
    address = json['address']?.toString();
    if (json['context'] != null) {
      final v = json['context'];
      final arr0 = <ResponseGeocodingBusquedaMapBoxModelFeaturesContext>[];
      v.forEach((v) {
        arr0.add(
            ResponseGeocodingBusquedaMapBoxModelFeaturesContext.fromJson(v));
      });
      context = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    if (placeType != null) {
      final v = placeType;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['place_type'] = arr0;
    }
    data['relevance'] = relevance;
    if (properties != null) {
      data['properties'] = properties!.toJson();
    }
    data['text'] = text;
    data['place_name'] = placeName;
    if (center != null) {
      final v = center;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['center'] = arr0;
    }
    if (geometry != null) {
      data['geometry'] = geometry!.toJson();
    }
    data['address'] = address;
    if (context != null) {
      final v = context;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['context'] = arr0;
    }
    return data;
  }
}

class ResponseGeocodingBusquedaMapBoxModel {
/*
{
  "type": "FeatureCollection",
  "query": [
    "republica"
  ],
  "features": [
    {
      "id": "address.1719818010",
      "type": "Feature",
      "place_type": [
        "address"
      ],
      "relevance": 0.679012,
      "properties": {
        "accuracy": "interpolated"
      },
      "text": "República De Costa Rica",
      "place_name": "República De Costa Rica 325, 45570 Tlaquepaque, Jalisco, Mexico",
      "center": [
        -103.306746
      ],
      "geometry": {
        "type": "Point",
        "coordinates": [
          -103.306746
        ],
        "interpolated": true
      },
      "address": "325",
      "context": [
        {
          "id": "postcode.11250836121368760",
          "text": "45570"
        }
      ]
    }
  ],
  "attribution": "NOTICE: © 2022 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained. POI(s) provided by Foursquare."
} 
*/

  String? type;
  List<String?>? query;
  List<ResponseGeocodingBusquedaMapBoxModelFeatures?>? features;
  String? attribution;

  ResponseGeocodingBusquedaMapBoxModel({
    this.type,
    this.query,
    this.features,
    this.attribution,
  });
  ResponseGeocodingBusquedaMapBoxModel.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['query'] != null) {
      final v = json['query'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      query = arr0;
    }
    if (json['features'] != null) {
      final v = json['features'];
      final arr0 = <ResponseGeocodingBusquedaMapBoxModelFeatures>[];
      v.forEach((v) {
        arr0.add(ResponseGeocodingBusquedaMapBoxModelFeatures.fromJson(v));
      });
      features = arr0;
    }
    attribution = json['attribution']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (query != null) {
      final v = query;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['query'] = arr0;
    }
    if (features != null) {
      final v = features;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['features'] = arr0;
    }
    data['attribution'] = attribution;
    return data;
  }
}
